### ISSUE TITLE
[CG] GENRE

### ISSUE THREAD

**Issue by hashpad** [kmdn/combining-linking-techniques#16]
server needed

**Comment by hashpad** [comment]
Server's Cuda version mismatch 
OSError: /local/users/*****/.local/lib/python3.7/site-packages/torch/lib/../../nvidia/cublas/lib/libcublas.so.11: symbol cublasLtGetStatusString version libcublasLt.so.11 not defined in file libcublasLt.so.11 with link time reference

Solution: see https://pytorch.org/get-started/previous-versions/#v182-with-lts-support

After fixing the environment and using the instructions:

Traceback (most recent call last):
  File "/local/users/****/GENRE/main.py", line 3, in <module>
    from model import Model
  File "/local/users/****/GENRE/model.py", line 6, in <module>
    from genre.fairseq_model import GENRE
  File "/local/users/****/GENRE/genre/fairseq_model.py", line 14, in <module>
    from fairseq import search, utils
  File "/local/users/****/GENRE/fairseq/fairseq/utils.py", line 20, in <module>
    from fairseq.modules.multihead_attention import MultiheadAttention
  File "/local/users/****/GENRE/fairseq/fairseq/modules/__init__.py", line 10, in <module>
    from .character_token_embedder import CharacterTokenEmbedder
  File "/local/users/****/GENRE/fairseq/fairseq/modules/character_token_embedder.py", line 11, in <module>
    from fairseq.data import Dictionary
  File "/local/users/****/GENRE/fairseq/fairseq/data/__init__.py", line 23, in <module>
    from .indexed_dataset import (
  File "/local/users/****/GENRE/fairseq/fairseq/data/indexed_dataset.py", line 112, in <module>
    6: np.float,
  File "/local/users/****/miniconda3/lib/python3.10/site-packages/numpy/__init__.py", line 313, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.

Changing np.float to float in the fairseq files results in the following:  

Traceback (most recent call last):
  File "/local/users/****/GENRE/main.py", line 3, in <module>
    from model import Model
  File "/local/users/****/GENRE/model.py", line 6, in <module>
    from genre.fairseq_model import GENRE
  File "/local/users/****/GENRE/genre/fairseq_model.py", line 15, in <module>
    from fairseq.models.bart import BARTHubInterface, BARTModel
  File "/local/users/****/GENRE/fairseq/fairseq/models/__init__.py", line 208, in <module>
    module = importlib.import_module("fairseq.models." + model_name)
  File "/local/users/****/miniconda3/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/local/users/****/GENRE/fairseq/fairseq/models/wav2vec/__init__.py", line 6, in <module>
    from .wav2vec import *  # noqa
  File "/local/users/****/GENRE/fairseq/fairseq/models/wav2vec/wav2vec.py", line 25, in <module>
    from fairseq.tasks import FairseqTask
  File "/local/users/****/GENRE/fairseq/fairseq/tasks/__init__.py", line 15, in <module>
    from .fairseq_task import FairseqTask, LegacyFairseqTask  # noqa
  File "/local/users/****/GENRE/fairseq/fairseq/tasks/fairseq_task.py", line 13, in <module>
    from fairseq import metrics, search, tokenizer, utils
ImportError: cannot import name 'metrics' from 'fairseq' (unknown location)
